In [70]:
import pandas as pd
import matplotlib.pyplot as plt
import plotly
import plotly.plotly as py
import plotly.graph_objs as go
import numpy as np
plotly.tools.set_credentials_file(username='yaghdev', api_key='BZvETrFTjtGisnoBsxAP')

In [71]:
year = ['2006', '2007', '2008', '2009', '2010', '2011', '2012', '2013', '2014', '2015', '2016', '2017']

usa_length = []

excel = pd.read_csv('C:/Users/Krishan/Downloads/FT50_WOS/insitutional_year_wise_all/edges/edges_2005.csv')    
insitute_2005 = excel.loc[(excel['Source'].apply(lambda x: x[-4:] == 'USA.')) & (excel['Target'].apply(lambda x: x[-4:] == 'USA.'))]
insitute_2005 = insitute_2005.sort_values(by='Weight', ascending=False)
insitute_2005 = insitute_2005.groupby(['Source']).agg({'Source':'count', 'Weight':'sum'}).sort_values(by='Weight', ascending=False)
insitute_2005.rename(columns={'Source': 'No of Insititute'}, inplace=True)
insitute_2005.reset_index(level=0, inplace=True)
 

for i in range(0, len(year)):    
    excel = pd.read_csv('C:/Users/Krishan/Downloads/FT50_WOS/insitutional_year_wise_all/edges/edges_'+str(year[i])+'.csv')    
    insitute_with_in_usa = excel.loc[(excel['Source'].apply(lambda x: x[-4:] == 'USA.')) & (excel['Target'].apply(lambda x: x[-4:] == 'USA.'))]
    insitute_with_in_usa = insitute_with_in_usa.groupby(['Source']).agg({'Source':'count', 'Weight':'sum'}).sort_values(by='Weight', ascending=False)
    insitute_with_in_usa.rename(columns={'Source': 'No of Insititute'}, inplace=True)
    insitute_with_in_usa.reset_index(level=0, inplace=True)
    insitute_2005 = pd.merge(insitute_2005, insitute_with_in_usa, on='Source', how='outer', suffixes=('2005' if i ==0 else year[i-1], year[i]))
insitute_2005 = insitute_2005.sort_values(by='No of Insititute2005', ascending=False)
all_sum = insitute_2005['No of Insititute2005'] + insitute_2005['No of Insititute2006']+insitute_2005['No of Insititute2007']+insitute_2005['No of Insititute2008']+insitute_2005['No of Insititute2009']+insitute_2005['No of Insititute2010']+insitute_2005['No of Insititute2011']+insitute_2005['No of Insititute2012']+insitute_2005['No of Insititute2013']+insitute_2005['No of Insititute2014']+insitute_2005['No of Insititute2015']+insitute_2005['No of Insititute2016']+insitute_2005['No of Insititute']
insitute_2005['all_insitute'] = all_sum

In [72]:
insitute_2005

,Source,No of Insititute2005,Weight2005,No of Insititute2006,Weight2006,No of Insititute2007,Weight2007,No of Insititute2008,Weight2008,No of Insititute2009,...,Weight2013,No of Insititute2014,Weight2014,No of Insititute2015,Weight2015,No of Insititute2016,Weight2016,No of Insititute,Weight,all_insitute
0,"Natl Bur Econ Res, Cambridge, MA 02138 USA.",66.0,99.0,63.0,92.0,74.0,107.0,50.0,54.0,47.0,...,47.0,73.0,81.0,45.0,48.0,48.0,59.0,60.0,68.0,747.0
1,"NBER, Cambridge, MA 02138 USA.",49.0,64.0,67.0,80.0,59.0,71.0,74.0,96.0,114.0,...,240.0,143.0,231.0,153.0,250.0,238.0,329.0,223.0,287.0,1634.0
2,"Univ Penn, Wharton Sch, Philadelphia, PA 19104...",46.0,55.0,54.0,62.0,37.0,45.0,46.0,52.0,53.0,...,62.0,66.0,72.0,46.0,49.0,48.0,49.0,31.0,33.0,644.0
4,"Stanford Univ, Grad Sch Business, Stanford, CA...",23.0,30.0,21.0,25.0,35.0,42.0,26.0,33.0,16.0,...,20.0,19.0,20.0,20.0,21.0,10.0,10.0,13.0,15.0,263.0
8,"Carnegie Mellon Univ, Tepper Sch Business, Pit...",23.0,23.0,9.0,9.0,8.0,8.0,15.0,16.0,8.0,...,10.0,11.0,11.0,16.0,17.0,10.0,10.0,20.0,21.0,176.0
6,"Duke Univ, Fuqua Sch Business, Durham, NC 2770...",21.0,24.0,20.0,22.0,21.0,24.0,23.0,26.0,26.0,...,20.0,20.0,21.0,11.0,11.0,13.0,13.0,16.0,16.0,253.0
10,"Duke Univ, Fuqua Sch Business, Durham, NC 2770...",20.0,22.0,10.0,11.0,10.0,11.0,12.0,12.0,11.0,...,7.0,6.0,6.0,6.0,6.0,8.0,9.0,6.0,6.0,121.0
7,"Univ Chicago, Grad Sch Business, Chicago, IL 6...",19.0,23.0,12.0,12.0,22.0,25.0,28.0,31.0,3.0,...,NaN,1.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,"Univ Chicago, Chicago, IL 60637 USA.",18.0,30.0,16.0,16.0,11.0,16.0,2.0,2.0,19.0,...,13.0,3.0,3.0,30.0,53.0,5.0,5.0,5.0,5.0,141.0
12,"Univ Maryland, Robert H Smith Sch Business, Co...",17.0,18.0,17.0,17.0,20.0,23.0,21.0,24.0,36.0,...,27.0,21.0,22.0,12.0,13.0,24.0,24.0,24.0,24.0,301.0
14,"Univ Notre Dame, Mendoza Coll Business, Notre ...",17.0,17.0,6.0,6.0,4.0,4.0,8.0,9.0,3.0,...,10.0,8.0,9.0,11.0,11.0,8.0,8.0,10.0,10.0,101.0
9,"Columbia Univ, Grad Sch Business, New York, NY...",17.0,23.0,23.0,26.0,15.0,18.0,18.0,21.0,13.0,...,6.0,4.0,4.0,3.0,3.0,7.0,7.0,4.0,4.0,150.0
11,"Arizona State Univ, WP Carey Sch Business, Tem...",17.0,19.0,7.0,7.0,15.0,15.0,19.0,23.0,16.0,...,23.0,10.0,10.0,10.0,10.0,12.0,12.0,9.0,9.0,196.0
3,"Harvard Univ, Cambridge, MA 02138 USA.",15.0,32.0,3.0,5.0,12.0,15.0,13.0,22.0,11.0,...,24.0,11.0,11.0,20.0,23.0,27.0,33.0,22.0,34.0,192.0
15,"Emory Univ, Goizueta Business Sch, Atlanta, GA...",14.0,16.0,13.0,15.0,10.0,11.0,10.0,10.0,10.0,...,13.0,16.0,19.0,7.0,7.0,4.0,4.0,7.0,8.0,141.0
19,"Texas A&M Univ, Mays Business Sch, College Stn...",13.0,13.0,11.0,11.0,7.0,8.0,15.0,15.0,16.0,...,10.0,4.0,4.0,11.0,12.0,19.0,21.0,16.0,16.0,150.0
24,"Univ Washington, Sch Business, Seattle, WA 981...",12.0,12.0,3.0,3.0,5.0,5.0,2.0,2.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,2.0,NaN
21,"Univ So Calif, Marshall Sch Business, Los Ange...",12.0,12.0,16.0,17.0,16.0,16.0,25.0,25.0,13.0,...,35.0,41.0,45.0,26.0,27.0,8.0,8.0,NaN,NaN,NaN
22,"Univ Pittsburgh, Katz Grad Sch Business, Pitts...",12.0,12.0,11.0,11.0,5.0,5.0,15.0,16.0,14.0,...,13.0,1.0,1.0,7.0,7.0,3.0,3.0,8.0,8.0,116.0
16,"Harvard Univ, Sch Business, Cambridge, MA 0213...",12.0,16.0,9.0,9.0,5.0,5.0,7.0,7.0,14.0,...,31.0,40.0,41.0,27.0,30.0,12.0,12.0,NaN,NaN,NaN
18,"Univ Penn, Philadelphia, PA 19104 USA.",11.0,13.0,11.0,12.0,17.0,18.0,3.0,3.0,9.0,...,2.0,11.0,13.0,12.0,14.0,7.0,9.0,20.0,24.0,127.0
17,"Univ Arizona, Tucson, AZ 85721 USA.",11.0,14.0,4.0,5.0,2.0,2.0,9.0,10.0,4.0,...,14.0,5.0,5.0,12.0,12.0,18.0,21.0,5.0,5.0,97.0
20,"Univ Minnesota, Carlson Sch Management, Minnea...",11.0,12.0,9.0,9.0,8.0,8.0,27.0,28.0,16.0,...,46.0,27.0,29.0,23.0,23.0,21.0,21.0,9.0,9.0,257.0
25,"Emory Univ, Atlanta, GA 30322 USA.",11.0,12.0,4.0,4.0,NaN,NaN,3.0,3.0,5.0,...,6.0,2.0,2.0,NaN,NaN,4.0,5.0,NaN,NaN,NaN
13,"Princeton Univ, Princeton, NJ 08544 USA.",11.0,17.0,2.0,3.0,8.0,9.0,4.0,4.0,2.0,...,14.0,10.0,10.0,14.0,18.0,6.0,8.0,11.0,12.0,105.0
27,"MIT, Sloan Sch Management, Cambridge, MA 02142...",11.0,11.0,2.0,2.0,5.0,5.0,2.0,2.0,1.0,...,9.0,10.0,10.0,5.0,5.0,2.0,2.0,5.0,5.0,61.0
28,"Harvard Univ, Sch Business, Boston, MA 02163 USA.",11.0,11.0,19.0,23.0,10.0,11.0,19.0,20.0,20.0,...,6.0,26.0,26.0,19.0,20.0,4.0,4.0,NaN,NaN,NaN
29,"Northwestern Univ, JL Kellogg Grad Sch Managem...",11.0,11.0,16.0,17.0,10.0,10.0,1.0,1.0,3.0,...,1.0,NaN,NaN,4.0,4.0,NaN,NaN,NaN,NaN,NaN
31,"Stanford Univ, Stanford, CA 94305 USA.",10.0,11.0,8.0,10.0,22.0,26.0,12.0,12.0,17.0,...,10.0,27.0,31.0,18.0,18.0,21.0,24.0,24.0,35.0,214.0
39,"Univ Calif Berkeley, Berkeley, CA 94720 USA.",10.0,10.0,6.0,7.0,7.0,10.0,7.0,8.0,10.0,...,14.0,7.0,7.0,15.0,15.0,18.0,24.0,15.0,24.0,152.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7704,"Microsoft Res, Los Angeles, CA USA.",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1.0,NaN
7705,"Microsoft Res, 641 Ave Amer, New York, NY 1001...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1.0,NaN
7706,"Univ Calif Riverside, Sch Business Adm, 900 Un...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1.0,NaN
7707,"Univ Calif Riverside, Sch Business Adm, Mkt, R...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1.0,NaN
7708,"Microsoft Corp, Anal & Experimentat Team, Redm...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1.0,NaN
7709,"Univ Calif San Diego, 9500 Gilman Dr,MC 0519, ...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1.0,NaN
7710,"Florida Int Univ, Coll Business Adm, Modesto A...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1.0,NaN
7711,"Univ Calif Davis, Dept Psychol, Davis, CA 9561...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1.0,NaN
7712,"NBER, CEPR, Cambridge, MA 02138 USA.",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1.0,NaN
7713,"Univ Arkansas, Supply Chain Management, Sam M ...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1.0,NaN
7714,"Georgia State Univ, Robinson Coll Business, De...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1.0,NaN
7715,"NBER, 369 Sage Hall,114 East Ave, Ithaca, NY 1...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1.0,NaN
7716,"Univ Baltimore, 1420 N Charles St, Baltimore, ...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1.0,NaN
7717,"Univ Baltimore, Merrick Sch Business, 1420 Nor...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1.0,NaN
7718,"Univ Buffalo, Sch Management, Dept Mkt, Buffal...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1.0,NaN
7719,"Univ Calif Angeles, Anderson Sch Management, L...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1.0,NaN
7720,"Univ Calif Berkeley, 545 Student Serv Bldg 190...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1.0,NaN
7721,"Columbia Univ, Fu Fdn Sch Engn & Appl Sci, New...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1.0,NaN
7722,"Univ Calif Berkeley, Dept Econ, 619 Evans Hall...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1.0,NaN
7723,"Columbia Univ, Dept Ind Engn & Operat Res, 500...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1.0,NaN
7724,"Univ Calif Berkeley, Econ Dept, 521 Evans Hall...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1.0,NaN
7725,"Univ Calif Berkeley, Fung Inst Engn Leadership...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1.0,NaN
7726,"Univ Calif Berkeley, Fung Inst Engn Leadership...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1.0,NaN
7727,"Univ Calif Berkeley, Goldman Sch Publ Policy, ...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1.0,NaN
7728,"NBER, 1050 Massachusetts Ave, Cambridge, MA 02...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1.0,NaN
7729,"Florida A&M Univ, Sch Business & Ind, Tallahas...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1.0,NaN
7730,"Univ Calif Berkeley, Haas Sch Business, Berkel...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1.0,NaN
7731,"Moodys Analyt, New York, NY USA.",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1.0,NaN
7732,"Columbia Univ, Columbia Business Sch, Business...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1.0,NaN
7733,"1208 Univ Oregon, Lundquist Coll Business, Uni...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1.0,NaN

In [73]:
all_sum

0        747.0
1       1634.0
2        644.0
4        263.0
8        176.0
6        253.0
10       121.0
7          NaN
5        141.0
12       301.0
14       101.0
9        150.0
11       196.0
3        192.0
15       141.0
19       150.0
24         NaN
21         NaN
22       116.0
16         NaN
18       127.0
17        97.0
20       257.0
25         NaN
13       105.0
27        61.0
28         NaN
29         NaN
31       214.0
39       152.0
         ...
7704       NaN
7705       NaN
7706       NaN
7707       NaN
7708       NaN
7709       NaN
7710       NaN
7711       NaN
7712       NaN
7713       NaN
7714       NaN
7715       NaN
7716       NaN
7717       NaN
7718       NaN
7719       NaN
7720       NaN
7721       NaN
7722       NaN
7723       NaN
7724       NaN
7725       NaN
7726       NaN
7727       NaN
7728       NaN
7729       NaN
7730       NaN
7731       NaN
7732       NaN
7733       NaN
Length: 7734, dtype: float64