In [76]:
import pandas as pd
import matplotlib.pyplot as plt
import plotly
import plotly.plotly as py
import plotly.graph_objs as go
import numpy as np
import plotly.figure_factory as ff
plotly.tools.set_credentials_file(username='yaghdev', api_key='BZvETrFTjtGisnoBsxAP')

In [77]:
year = ['2006', '2007', '2008', '2009', '2010', '2011', '2012', '2013', '2014', '2015', '2016', '2017']
ary = ['Accounting','Economics','Economics, Management', 'Entrepreneurship', 'Ethics', 'Finance', 'Human Resources', 'International Business', 'Management','Marketing', 'Operations & InformationSystems', 'Organizational Behaviour']

excel_1 = pd.read_excel('C:/Users/Krishan/Downloads/FT50_WOS/insitutional_year_wise_all/Insitutional_2005.xlsx')
excel_1 = excel_1.loc[excel_1['Insitute'].apply(lambda x: x[-4:] == 'USA.')].iloc[:,[0, 4]]
 
for i in range(0, len(year)):    
    excel_2 = pd.read_excel('C:/Users/Krishan/Downloads/FT50_WOS/insitutional_year_wise_all/Insitutional_'+str(year[i])+'.xlsx')
    excel_2 = excel_2.loc[excel_2['Insitute'].apply(lambda x: x[-4:] == 'USA.')]
    excel_1 = pd.merge(excel_1, excel_2.iloc[:,[0, 4]], on='Insitute', how='outer', suffixes=('2005' if i ==0 else year[i-1], year[i]))
      
excel_1 = excel_1.sort_values(by='page rank', ascending=False) 

# excel_2005 = pd.read_excel('C:/Users/Krishan/Downloads/FT50_WOS/insitutional_year_wise_all/Insitutional_2017.xlsx')
# excel_2005 = excel_2005.loc[excel_2005['Insitute'].apply(lambda x: x[-4:] == 'USA.')] 
# excel_2005 = excel_2005.sort_values(by='page rank', ascending=False)

In [82]:
excel_1.iloc[:,[0, 13]][:5]

                                               Insitute  page rank
692                      NBER, Cambridge, MA 02138 USA.   0.009761
723         Natl Bur Econ Res, Cambridge, MA 02138 USA.   0.002259
4436                          CEPR, Washington, DC USA.   0.001571
5215  Univ Chicago, Booth Sch Business, Chicago, IL ...   0.001449
1547  Univ Penn, Wharton Sch, Philadelphia, PA 19104...   0.001290

In [83]:
excel_1[:50].corr(method='pearson', min_periods=1)

,page rank2005,page rank2006,page rank2007,page rank2008,page rank2009,page rank2010,page rank2011,page rank2012,page rank2013,page rank2014,page rank2015,page rank2016,page rank
page rank2005,1.000000,0.942143,0.948013,0.835155,0.818562,0.870253,0.754569,0.789979,0.701775,0.777670,0.694945,0.633420,0.619432
page rank2006,0.942143,1.000000,0.910924,0.884228,0.878993,0.899524,0.849798,0.848497,0.796252,0.859142,0.779747,0.735778,0.721552
page rank2007,0.948013,0.910924,1.000000,0.842392,0.836901,0.896214,0.764380,0.809886,0.701031,0.774587,0.692023,0.640217,0.629480
page rank2008,0.835155,0.884228,0.842392,1.000000,0.907790,0.856152,0.883845,0.840173,0.854543,0.854855,0.813341,0.785029,0.755537
page rank2009,0.818562,0.878993,0.836901,0.907790,1.000000,0.909120,0.952289,0.941242,0.919004,0.934355,0.897816,0.879379,0.857713
page rank2010,0.870253,0.899524,0.896214,0.856152,0.909120,1.000000,0.900817,0.927346,0.862401,0.890858,0.808985,0.786495,0.767463
page rank2011,0.754569,0.849798,0.764380,0.883845,0.952289,0.900817,1.000000,0.931353,0.949711,0.956826,0.937507,0.926907,0.912896
page rank2012,0.789979,0.848497,0.809886,0.840173,0.941242,0.927346,0.931353,1.000000,0.943713,0.910497,0.908595,0.860313,0.846334
page rank2013,0.701775,0.796252,0.701031,0.854543,0.919004,0.862401,0.949711,0.943713,1.000000,0.976786,0.962955,0.953802,0.935540
page rank2014,0.777670,0.859142,0.774587,0.854855,0.934355,0.890858,0.956826,0.910497,0.976786,1.000000,0.933383,0.936598,0.923598
page rank2015,0.694945,0.779747,0.692023,0.813341,0.897816,0.808985,0.937507,0.908595,0.962955,0.933383,1.000000,0.956965,0.949913
page rank2016,0.633420,0.735778,0.640217,0.785029,0.879379,0.786495,0.926907,0.860313,0.953802,0.936598,0.956965,1.000000,0.985949
page rank,0.619432,0.721552,0.629480,0.755537,0.857713,0.767463,0.912896,0.846334,0.935540,0.923598,0.949913,0.985949,1.000000